const autos = [
  {
    marca: "Audi",
    image: "../img/Audi-A1-White.png",
    modelo: "A1",
    year: 2010,
    precio: 50000,
    puertas: 4,
    color: "Blanco",
    transmision: "automatico",
  },
  {
    marca: "Audi",
    image: "../img/Audi-Tt-Gray.png",
    modelo: "Tt",
    year: 2014,
    precio: 80000,
    puertas: 4,
    color: "gris",
    transmision: "automatico",
  },
  {
    marca: "Audi",
    image: "../img/Audi-Sideview-Black.png",
    modelo: "Sideview",
    year: 2015,
    precio: 20000,
    puertas: 2,
    color: "Negro",
    transmision: "automatico",
  },
  {
    marca: "Audi",
    image: "../img/Audi-Tt-Red.png",
    modelo: "Tt",
    color: "Red",
    transmision: "automatico",
    year: 2014,
    precio: 80000,
    puertas: 4,
  },
  {
    marca: "Chevrolet",
    image: "../img/Chevrolet-Corvette-White.png",
    modelo: "Corvette",
    year: 2016,
    precio: 60000,
    puertas: 4,
    color: "Blanco",
    transmision: "automatico",
  },
  {
    marca: "Chevrolet",
    image: "../img/Chevrolet-Sport-yellow.png",
    modelo: "Sport",
    year: 2015,
    precio: 25000,
    puertas: 4,
    color: "Amarillo",
    transmision: "automatico",
  },
  {
    marca: "Lamborgini",
    image: "../img/Lamborghini-Black.png",
    modelo: "-",
    year: 2018,
    precio: 200000,
    puertas: 2,
    color: "Negro",
    transmision: "Automatico",
  },
  {
    marca: "Lamborgini",
    image: "../img/Lamborghini-Gray.png",
    modelo: "-",
    year: 2018,
    precio: 200000,
    puertas: 2,
    color: "Gris",
    transmision: "Automatico",
  },
  {
    marca: "Lamborgini",
    image: "../img/Lamborghini-Orange.png",
    modelo: "-",
    year: 2018,
    precio: 200000,
    puertas: 2,
    color: "Naranja",
    transmision: "Automatico",
  },
  {
    marca: "Mercedes",
    image: "../img/Mercedes-Luxury-Gray.png",
    modelo: "Luxury",
    year: 2017,
    precio: 100000,
    puertas: 4,
    color: "Gris",
    transmision: "manual",
  },
  {
    marca: "Suzuki",
    image: "../img/Suzuki-Front-Red.png",
    modelo: "Front",
    year: 2020,
    precio: 25000,
    puertas: 2,
    color: "Rojo",
    transmision: "manual",
  },
  {
    marca: "Suzuki",
    image: "../img/Suzuki-Swift-White.png",
    modelo: "Swift",
    year: 2018,
    precio: 45000,
    puertas: 4,
    color: "Blanco",
    transmision: "automatico",
  },
  {
    marca: "Suzuki",
    image: "../img/Suzuki-Sx4-Orange.png",
    modelo: "Sx4",
    year: 2019,
    precio: 90000,
    puertas: 4,
    color: "Naranja",
    transmision: "automatico",
  },
  {
    marca: "Toyota",
    image: "../img/Toyota-C-HR-Front-Black.png",
    modelo: "C-HR",
    year: 2017,
    precio: 60000,
    puertas: 2,
    color: "Negro",
    transmision: "manual",
  },
  {
    marca: "Toyota",
    image: "../img/Toyota-Prius-Black.png",
    modelo: "Prius",
    year: 2015,
    precio: 100000,
    puertas: 2,
    color: "Negro",
    transmision: "automatico",
  },
];
